### ISSUE TITLE
Congrats and additional questions on the datasets you used in the study!

### ISSUE THREAD

**Issue by black0017** [sxzrt/CIFAR-10-W#1]
Hello and congrats for the amazing contribution to the community! I am really glad i discovered your work today.

I have 2 very simple questions from table 1 in https://arxiv.org/pdf/2310.04414 :

<img width="859" alt="image" src="https://github.com/sxzrt/CIFAR-10-W/assets/13345132/dc13e9bb-736b-4c18-97f5-b37fe4395779">

1. What is CIFAR-10.1-C from Hendrycks & Dietterich, 2019 with 190K images? Is it just random 5K samples from each of the 19 datasets?
2. CIFAR10-W consists of ~608K samples. Have you proposed any subset benchmark of this so that i can evaluate my classifier on? Would be curious to see how would you go about sampling from 180 different domains. Something around 190K images would be nice to be similar to the size of Hendrycks & Dietterich, 2019.

Your feedback is highly appreciated!

By the way in the readme's repo the gdrive link is hidden in the readme due to a small markdown error! You can very easily fix that :) 

Thank you so much @sxzrt  and have a nice day!

Nikolas.

**Comment by sxzrt** [comment]
Hi Nikolas,

Thank you very much for your kind words and your interest in CIFAR-10-W. I’ll do my best to provide you with the answers.

For question 1), we referred to the code from  https://github.com/hendrycks/robustness/blob/8190fe329f5f072a06e3a2aea02bb5dda69aed9f/ImageNet-C/create_c/make_cifar_c.py#L422-L442 to generate the CIFAR-10.1-C dataset. CIFAR-10.1-C consists of 190,000 images since it includes 19 corruptions and each corruption has 10,000 images from CIFAR-10.1 dataset.

2) We do not have a fixed subset for evaluation because we believe that researchers can create subsets based on their specific needs. However, we attempted to randomly sample 100 images from each class across the 180 domains listed in the paper's Table 8 (If fewer than 100 images are available, we will use all the data for that particular class). If you want to use a subset, there are two options: you can directly follow the way we used in Table 8 or sample data based on the ordinal imbalance ratio. 


Finally, thank you for pointing out the issue. If you have any questions, please feel free to reach out to us at any time. :)

**Comment by black0017** [comment]
Hello, and thanks a lot for getting back to me so fast!!!

1) So you have created the corrupted images yourself instead of downloading the corrupted files from the cloud that they provide in their repo, is that right?

2) Can you point me to the details of the `ordinal imbalance ratio` in the paper? I was thinking of taking a small subset of something like 10% per image folder. Do I lose something if I take random splits per folder instead of sampling from the  180 domains? I need to take a better look on the paper i guess! :) My goal is to have a representative subset that I can benchmark very quickly with different backbones.

**Comment by sxzrt** [comment]
Hello,

1. If the corrupted files are provided for download, we use the provided versions, such as CIFAR-10-C https://github.com/hendrycks/robustness/tree/8190fe329f5f072a06e3a2aea02bb5dda69aed9f. However, we did not find a publicly available version for CIFAR-10.1-C, so we used the code mentioned in the previous reply to generate this set.

2. Fig.1 shows the statistics for different sets in CIFAR-W-10, highlighting the imbalance in the distribution of the datasets. The minimum set size is about 300 images, and the maximum set size is about 8,000 images. Alternatively, if you have downloaded the CIFAR-W-10 datasets, you can analyze the number of data to obtain other information you need.

**Comment by sxzrt** [comment]
Thank you so much for sharing this. This is incredibly helpful. I will definitely add it to the repository. Your contribution will be valuable for other researchers as well. Thanks again!

**Comment by black0017** [comment]
1. Perfect. I hadn't realized that CIFAR10C and CIFAR10.1-C are different datasets. I had the impression that CIFAR10.1-C was simply a subset of CIFAR10C, thanks for pointing that out @sxzrt !!!
2. OK makes sense.

Feel free to close the issue since all my questions were addressed, thanks!!!
